# Generated by Django 4.2.6 on 2023-10-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delivery_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DELIVERED", "Delivered"),
                            ("PICKED", "Picked"),
                            ("AT_VENDOR", "At Vendor"),
                            ("ASSIGNED", "Assigned"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.order")),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="vendor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.vendor"),
        ),
        migrations.CreateModel(
            name="DelayReports",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_type", models.IntegerField()),
                ("new_delivery_time", models.DateTimeField()),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.order")),
            ],
        ),
        migrations.CreateModel(
            name="DelayQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("agent", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.agent")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.order")),
            ],
        ),
    ]
